// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/kittichanr/go-wire/greeter"
)

// Injectors from wire.go:

func InitializeApplication(ctx context.Context) (greeter.Event, func(), error) {
	message := greeter.NewMessage()
	greeterGreeter := greeter.NewGreeter(message)
	event := greeter.NewEvent(greeterGreeter)
	return event, func() {
	}, nil
}
